-- decision-log.md D78, product/99-rfc/0016-inventory-unit-bidirectional-correction.md.
-- Supersedes 20260918010000_inventory_unit_removal.sql's decrease-only
-- correct_product_available_count RPC with a bidirectional one, backed by a
-- new append-only InventoryCorrection ledger (internal-only entity owned by
-- Product, same class as AllocationMovement-under-EventAllocation) and a new
-- Lot.source field distinguishing a correction-generated Lot from a real
-- supplier receipt. Never rewrites InventoryEntry.quantity or touches any
-- Sale/EventAllocation/Claim; decrease stays available-only (never
-- reserved), increase mints new units through the existing, unmodified
-- InventoryEntry -> InventoryUnit generation path.

alter table public.lots
  add column if not exists source text not null default 'supplier_delivery'
    check (source in ('supplier_delivery', 'correction'));

comment on column public.lots.source is
  'D78/RFC 0016 — supplier_delivery (default) for a real receipt via '
  'commit_lot(); correction for a Lot generated by an upward '
  'InventoryCorrection via correct_product_available_count(). Both flow '
  'through the identical InventoryEntry -> InventoryUnit generation, never '
  'a second unit-creation path. Never shown to the merchant.';

create table if not exists public.inventory_corrections (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id),
  product_id uuid not null references public.products (id),
  type text not null check (type in ('increase', 'decrease')),
  quantity_delta integer not null,
  unit_ids uuid[] not null,
  source_lot_id uuid references public.lots (id),
  created_at timestamptz not null default now()
);

comment on table public.inventory_corrections is
  'D78/RFC 0016 — append-only ledger entity internal to Product (not an '
  'aggregate root, same class as AllocationMovement-under-EventAllocation). '
  'unit_ids is unconditional on every row: the FIFO-selected units flipped '
  'to removed on a decrease, or the newly generated units on an increase. '
  'source_lot_id is set only on an increase, pointing at the '
  'source=''correction'' Lot that generated those units. Written once, '
  'never mutated. Only ever written inside '
  'correct_product_available_count()''s own atomic transaction.';

create index if not exists inventory_corrections_business_id_idx
  on public.inventory_corrections (business_id);

create index if not exists inventory_corrections_product_id_idx
  on public.inventory_corrections (product_id);

-- Same class as lots/inventory_entries — OWNER-only reads, no
-- INSERT/UPDATE/DELETE policy for any role; only ever written inside
-- correct_product_available_count()'s own SECURITY DEFINER transaction.
alter table public.inventory_corrections enable row level security;

create policy inventory_corrections_select on public.inventory_corrections
  for select
  using (public.is_active_owner_of(business_id));

grant select on public.inventory_corrections to authenticated;

-- Target-based, not delta-based: the client sends the absolute
-- "disponibles" figure it wants (D78/inventory.md §3.6's own "Cantidad
-- disponible actual"), not "add/remove N." The RPC recomputes the real
-- current available count server-side and applies exactly the delta needed
-- to reach that target:
--   delta > 0 (target above current) -> increase: mints new available
--     units via a real, source='correction' Lot/InventoryEntry, through
--     the same generation mechanism commit_lot() already uses. Unconstrained
--     by construction (D78) — never touches an existing row, so no race is
--     reachable and the full requested delta always applies.
--   delta < 0 (target below current) -> decrease: FIFO-selects |delta|
--     available units (D5), deletes their nfc_tags (tag release, D77),
--     flips them to 'removed'. Same "conditional write, zero-rows-affected
--     = already moved on" convergence as assign_tag_to_next_pending_unit/
--     commitAllocation() — if fewer units are actually available by the
--     time this runs (a concurrent Sale elsewhere), it removes only what's
--     left to remove and returns the real applied delta, never errors.
--   delta = 0 -> no-op, no ledger row written (a correction left untouched
--     costs nothing, matching INV-Q1's own zero-cost-for-the-common-case
--     discipline).
-- Only 'available' units are ever eligible for a decrease — never
-- 'reserved' (an in-flight Sale or EventAllocation elsewhere), the same
-- discipline assign_tag_to_next_pending_unit/commitAllocation() already
-- enforce.
create or replace function public.correct_product_available_count(
  p_business_id uuid,
  p_product_id uuid,
  p_target_available_count integer,
  p_idempotency_key uuid
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_key_id uuid;
  v_existing_result jsonb;
  v_current_count integer;
  v_delta integer;
  v_lot_id uuid;
  v_received_at timestamptz := now();
  v_unit_ids uuid[];
  v_applied_delta integer;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  if not public.is_active_owner_of(p_business_id) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if p_target_available_count < 0 then
    raise exception 'invalid_target_count' using errcode = '22023';
  end if;

  insert into public.idempotency_keys (id, business_id, operation)
  values (p_idempotency_key, p_business_id, 'correct_product_available_count')
  on conflict (id) do nothing
  returning id into v_key_id;

  if v_key_id is null then
    select result into v_existing_result
    from public.idempotency_keys
    where id = p_idempotency_key;

    if v_existing_result is null then
      raise exception 'idempotent_operation_in_progress' using errcode = '55000';
    end if;

    return (v_existing_result ->> 'applied_delta')::integer;
  end if;

  select count(*) into v_current_count
  from public.inventory_units
  where business_id = p_business_id
    and product_id = p_product_id
    and status = 'available';

  v_delta := p_target_available_count - v_current_count;

  if v_delta = 0 then
    update public.idempotency_keys
    set result = jsonb_build_object('applied_delta', 0)
    where id = p_idempotency_key;
    return 0;

  elsif v_delta > 0 then
    insert into public.lots (business_id, received_at, source)
    values (p_business_id, v_received_at, 'correction')
    returning id into v_lot_id;

    insert into public.inventory_entries (business_id, lot_id, product_id, quantity)
    values (p_business_id, v_lot_id, p_product_id, v_delta);

    with new_units as (
      insert into public.inventory_units (business_id, product_id, lot_id, status, received_at)
      select p_business_id, p_product_id, v_lot_id, 'available', v_received_at
      from generate_series(1, v_delta)
      returning id
    )
    select array_agg(id) into v_unit_ids from new_units;

    insert into public.inventory_corrections
      (business_id, product_id, type, quantity_delta, unit_ids, source_lot_id)
    values
      (p_business_id, p_product_id, 'increase', v_delta, v_unit_ids, v_lot_id);

    v_applied_delta := v_delta;

  else
    with candidates as (
      select id
      from public.inventory_units
      where business_id = p_business_id
        and product_id = p_product_id
        and status = 'available'
      order by received_at asc
      limit abs(v_delta)
      for update skip locked
    ),
    tag_release as (
      delete from public.nfc_tags
      where unit_id in (select id from candidates)
    ),
    removed as (
      update public.inventory_units
      set status = 'removed'
      where id in (select id from candidates)
      returning id
    )
    select array_agg(id) into v_unit_ids from removed;

    v_applied_delta := -coalesce(array_length(v_unit_ids, 1), 0);

    if v_applied_delta < 0 then
      insert into public.inventory_corrections
        (business_id, product_id, type, quantity_delta, unit_ids, source_lot_id)
      values
        (p_business_id, p_product_id, 'decrease', v_applied_delta, v_unit_ids, null);
    end if;
  end if;

  update public.idempotency_keys
  set result = jsonb_build_object('applied_delta', v_applied_delta)
  where id = p_idempotency_key;

  return v_applied_delta;
end;
$$;

revoke execute on function public.correct_product_available_count(uuid, uuid, integer, uuid) from public;
grant execute on function public.correct_product_available_count(uuid, uuid, integer, uuid) to authenticated;
